org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.12.101-hotspot

mod.id=lifeseries
mod.name=Evil Life Series
mod.group=net.mat0u5.lifeseries
mod.version=1.5.9
mod.version_prefix=
mod.version_suffix=
mod.authors=Mat0u5
mod.contributors=iamdabirb
mod.license=MIT
mod.description=A one-to-one recreation of Grian's Life Series in Fabric, Forge and NeoForge.
mod.sources_url=https://github.com/Mat0u5/LifeSeries
mod.homepage_url=https://modrinth.com/mod/life-series
mod.issues_url=https://github.com/Mat0u5/LifeSeries/issues
mod.discord_url=https://discord.gg/QWJxfb4zQZ

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]

# Optional Dependencies
# https://modrinth.com/plugin/simple-voice-chat/versions
# https://modrinth.com/mod/carpet/versions
deps.fabric-api=[VERSIONED]
deps.voicechat=[VERSIONED]
deps.carpet=[VERSIONED]
deps.carpet_bot_relog=1.0.1

# Publishing
publish.dryrun=false
publish.changelog.link=https://mat0u5.github.io/LifeSeries-docs/changelog/?v=1.5.8-1.5.9

#publish.modrinth.id=RLDqKhd4
publish.modrinth.id=aLasQi8P
publish.curseforge.id=1151647

publish.modrinth=true
publish.curseforge=true
publish.github=true
publish.discord=true

publish.release.fabric=stable
publish.release.neoforge=stable
publish.release.forge=stable

publish.github.prerelease=false
publish.discord.dev=false
publish.discord.ping=true

publish.github.branch=main
publish.github.target=Mat0u5/LifeSeries
